# Generated by Django 4.2 on 2025-03-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContryData',
            new_name='CountryData',
        ),
    ]
