# Generated by Django 4.2 on 2025-03-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_contrydata_countrydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': '각 나라별 인구 데이터'},
        ),
    ]
